sudo: required
language: java
services:
  - docker

jdk:
- openjdk11

notifications:
  email: false

script: ./scripts/build.sh

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/push.sh $TRAVIS_TAG
  on:
    tags: true
