sudo: required
language: java
services:
  - docker

jdk:
- openjdk8

notifications:
  email: false

env:
  global:
  - secure: m4gBucLf7Lh5vzCsTHqgj5a06mBMaRYh9e1D0EIvR8gKcbtGC471yfiX6vKhDbYxU+kHIqrRJ1OH6hoYl+Y4PnG8dNV6x86SP5cHj5mz+gY1jYJz5vj24PZnGYU6lnl8328AsBuOGI4umjFFiNASI/C5KuwRTTku+01+G7HE1VJMX5ny/LJ/K5xJ0UCa6OglHDa0mBbSl3ieKEoIpSCeIYdirSDEqkXzNr6kYgo0y1Sdr9Utyc93Pb145ktM61+kvL1fHixYSl06O4wZPVMp9Ol2DEd0V4l5kdY+DyWIa/MYQVZ521wsI2P8brdC/QKn0ZgWv/isZvFipWZMZosa0Srf2X/EdtzcSMBH8gl91YTshlAz2nyxmI3EVCXZK5XzJzCVgYVLIriuXs2ZsrK4ATeiE3rSF1domkSgTaSaKuBNWTUDe0v2+IqeRRAjviOnALZTFacNPn92jdZztxkPX6kfjC60pSufZ4gXz98lZbykIqoWzsKDjW7GDpCSgUqzHpIDpw57NxlZR57NPJHclGGhDUq4e98G6LvEPnckKfC4CXtsQdgz0pF3P4MSLtp85F/WEYZTsbiVmorHlruDpRpQz695DXjMgB/rj9EKR1chbHPruQb2CZjILDo0Lse1sRVyLLMewVpF9SAQppx1ie6SbmVN2l0/plapocBYxVQ=
  - secure: rCoPVidCppZRrlTKfuYZlpbEhGUaTO22Zvrh72RODZ0KPAqElnaM6zZNgToIZWMS7KL0PsnbrjWN2F7+YNHhArUR41WxlFMF/LNWUcJWLlgHSLeEVFrxk8qMLtGyrMFSHKaHrXREqu2Dw/gXpp2Tc7wB3hksQRn9R4yoS/2DcY6g450lMgGimrJH5wrwvfzJPz6Adcy2iy2G9r5QyOsko5j3um5qzPsMOBaJyyleAI8RjPiyYVrdKSI4L65Gg7l9hUAw+Y0Lk1ybpnj/ahgwiQL14Wb/tww7akz/tKkztE7T9qqucKmApTR15dK2CZ/vZfH915OMFqTVFuA2XTOZxnHIZnFknA1gzudZpb4YaxSet73Dr/gynuK6NuRnTFLq7c2NzlQaZhpmHETS4Ei1Akhctyxd11s9rNvdNuZLl8Uz3ZB9Zjodv7iANvh6yD0EeO3kPWJh/fiWTBXOoHJpQ+u1QTjkLnl1r/8cpLXG+WjNSvrlknWn6YmxSoXYbHpItuLB+okEF4b9hk4w7rWLFdEH0acJHzD4bL6qkWtQWCCRI+BrYljIwj+iPakmeCaw6T7IiHzpFnJGfNb/V/Mzl0GFDZXr6cDR8jdU57PBiWTyQykFmVM+GbVmI8ywTlyYh1noNUI0ol1lSD52hWU8OXVMt5Pi/aAaQkOzvTwxGTg=

script: .travis/build_script.sh

after_success: .travis/push_script.sh
