sudo: required
language: java
services:
  - docker

jdk:
- openjdk11

notifications:
  email: false

script: scripts/build.sh

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/push.sh $TRAVIS_TAG 'docker.io/norsknettarkiv/veidemann-contentwriter'
  on:
    tags: true
