sudo: required
language: java
services:
  - docker

jdk:
- openjdk11

notifications:
  email: false

after_success: bash .travis/build_script.sh

deploy:
  provider: script
  script: bash .travis/push_script.sh $TRAVIS_TAG
  on:
    tags: true
    branch: master
