apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-contentwriter
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 100
      volumes:
        - emptyDir: {}
          name: workdir
        - name: warcs
          persistentVolumeClaim:
            claimName: veidemann-warcs
        - name: log4j-config
          configMap:
            name: release-name-veidemann
            items:
              - key: log4j2.xml
                path: log4j2.xml
      containers:
        - name: veidemann-contentwriter
          image: veidemann-contentwriter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 8080
          volumeMounts:
            - mountPath: /workdir
              name: workdir
            - mountPath: /warcs
              name: warcs
            - name: log4j-config
              mountPath: /veidemann/config/log4j2.xml
              subPath: log4j2.xml
          envFrom:
            - secretRef:
                name: release-name-veidemann-rethinkdb-env
                optional: false
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DB_HOST
              value: $(RETHINKDB_HOST)
            - name: DB_PORT
              value: "28015"
            - name: DB_NAME
              value: "veidemann"
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TERMINATION_GRACE_PERIOD_SECONDS
              value: "60"
            - name: WARC_WRITER_POOL_SIZE
              value: "2"
            - name: JAEGER_SERVICE_NAME
              value: "veidemann-contentwriter"
            - name: JAEGER_AGENT_HOST
              value: "localhost"
            - name: JAEGER_AGENT_PORT
              value: "6831"
